### ISSUE TITLE
how to get the smallest set of disjoint relations？

### ISSUE THREAD

**Issue by RickRen-rpr** [allenai/drug-combo-extraction#46]
how to use a greedy heuristic of choosing the smallest set of disjoint relations whose union covers as many drug entities as possible in the sentence？
Excuse me, I'm confused about this issue, could you please tell me how this process works? If possible, could you give a simple example? thanks

**Comment by aryehgigi** [comment]
First of all I'm so sorry for the late response @RickRen-rpr  (I wasn't on the watch-list for some reason, now its fixed, so thank you!)

Regarding your question, as you can see in the code and documentation [here](https://github.com/allenai/drug-combo-extraction/blob/main/common/utils.py#L314), we choose the largest drug-group **without** "NO_COMB" label. then we repeat this process for the remaining drugs. Notice this is a greedy algorithm, so its not promised that you will get maximum coverage, instead it will give you minimum groups with as much coverage as possible (given this amount of groups).

**An example:**
lets say we have 5 drugs in the sentence. let say these are the model predictions: POS_COMB: {1,2,3}, {3,4}. OTHER_COMB: {1,2} (notice no prediction included drug 5 and notice the conflicting predictions labels and spans).
According to the heuristic, first we find the largest group that is not NO_COMB (i.e. {1,2,3}) then we continue with the remaining drugs: 4 and 5. Since no group includes drug 5, we finish the procedure with the single {1,2,3} group.
Notice this is not the maximum coverage as we can get a larger coverage with the non conflicting groups {1,2} and {3,4}, this is the downside of the greedy heuristic, but we are guaranteed to have minimal group count (only one in this case) and that it includes the maximum amount of drugs **per this group count** (3 drugs for a single group).

Notice that this is **our** decision on how to label the relations using the possibly conflicting model outputs, but you/other participants can use different heurisitcs/algorithms/prediction-methods to achieve better performance.
